import Head from "next/head";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export default function  Layout({ children }) {
  const basePath = process.env.BASE_PATH

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href={`${basePath}/images/snake-icon.ico`} />
      </Head>

      <main>
        <Header />
        { children }
        <Footer />
      </main>
    </>
  );
}
