import Head from "next/head";
import Script from 'next/script';
import Banner from "@/components/Banner";
import Arena from "@/components/Arena";
import Market from "@/components/Market";
import Header from "@/components/layout/Header";
import Map from "@/components/Map";
import Footer from "@/components/layout/Footer";
import Token from '@/components/Token';
import Roadmap from '@/components/Roadmap';
import Join from '@/components/Join';

export default function Home() {
  const basePath = process.env.BASE_PATH

  return (
    <>
      <Head>
        <title>PonPonSnake Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href={`${process.env.BASE_PATH}/images/snake-icon.ico`} />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js" />
      </Head>

      <main>
        <Header />
        <Banner />
        <Arena />
        <Market />
        <Map />
        <Token />
        <Roadmap />
        <div className="bottom-area">
          <Join />
          <Footer />
        </div>
      </main>
    </>
  );
}
